asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:22:07 +0000] "POST /find HTTP/1.1" 200 677144 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:24:25 +0000] "POST /find HTTP/1.1" 200 677144 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:27:57 +0000] "POST /find HTTP/1.1" 200 677144 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:29:09 +0000] "POST /find HTTP/1.1" 200 677144 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:31:53 +0000] "POST /find HTTP/1.1" 200 677144 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:34:44 +0000] "POST /find HTTP/1.1" 200 351 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:36:04 +0000] "POST /find HTTP/1.1" 200 351 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:37:13 +0000] "POST /find HTTP/1.1" 200 351 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:37:33 +0000] "POST /find HTTP/1.1" 200 351 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:44:52 +0000] "POST /find HTTP/1.1" 200 351 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:20:46:51 +0000] "POST /find HTTP/1.1" 200 13038401 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:21:03:44 +0000] "POST /find HTTP/1.1" 200 16944714 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:21:12:05 +0000] "POST /find HTTP/1.1" 200 16944714 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:21:16:40 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:21:21:11 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [04/Sep/2020:21:21:56 +0000] "POST /find HTTP/1.1" 200 16944714 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [05/Sep/2020:21:06:25 +0000] "GET / HTTP/1.1" 405 203 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [05/Sep/2020:21:06:26 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [05/Sep/2020:21:07:43 +0000] "POST / HTTP/1.1" 200 412 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:51:35 +0000] "GET / HTTP/1.1" 405 203 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:51:35 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:52:28 +0000] "GET / HTTP/1.1" 405 203 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:53:17 +0000] "GET / HTTP/1.1" 405 203 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:53:30 +0000] "GET / HTTP/1.1" 405 203 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:54:07 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:07:57:04 +0000] "GET / HTTP/1.1" 405 203 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:08:01:56 +0000] "GET / HTTP/1.1" 200 412 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:16:34:02 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:16:34:12 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:16:34:22 +0000] "POST /find HTTP/1.1" 200 12071 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:22:57:50 +0000] "GET / HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:22:58:16 +0000] "POST /find HTTP/1.1" 200 16944714 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [06/Sep/2020:22:59:23 +0000] "GET / HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:38:24 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:38:30 +0000] "GET / HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:38:31 +0000] "GET / HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 61, in handle_post
    final_data = await launch_processors(brand, data)
  File "a:\git\brand\app.py", line 30, in launch_processors
    async with Pool(cpu_count()) as p:
AttributeError: __aexit__
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:39:22 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:39:54 +0000] "GET / HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 YaBrowser/20.8.2.92 Yowser/2.5 Safari/537.36"
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 61, in handle_post
    final_data = await launch_processors(brand, data)
  File "a:\git\brand\app.py", line 30, in launch_processors
    async with Pool(cpu_count()) as p:
AttributeError: __aexit__
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:40:24 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [08/Sep/2020:18:41:55 +0000] "POST /find HTTP/1.1" 200 16944714 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 68, in handle_post
    token = json.loads(final_data['token'])
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:27:53 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 68, in handle_post
    token = json.loads(final_data['token'])
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:28:05 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 68, in handle_post
    token = json.loads(final_data['token'])
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:28:21 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 68, in handle_post
    token = json.loads(final_data['token'])
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:29:09 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 70, in handle_post
    return web.Response(text=json.dumps(final_data, ensure_ascii=False))
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:30:52 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 70, in handle_post
    return web.Response(text=json.dumps(final_data, ensure_ascii=False))
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:31:24 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 70, in handle_post
    return web.Response(text=json.dumps(final_data, ensure_ascii=False))
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:32:18 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 70, in handle_post
    return web.Response(text=json.dumps(final_data, ensure_ascii=False))
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\algorithm\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:32:54 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:34:51 +0000] "POST /find HTTP/1.1" 200 1638 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:35:49 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:44:20 +0000] "POST /find HTTP/1.1" 200 154 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:44:52 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 75, in handle_post
    final_data = await adding_headers(final_data)
  File "a:\git\brand\app.py", line 32, in adding_headers
    await final_data.insert(0, headers_row)
TypeError: object NoneType can't be used in 'await' expression
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:45:47 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "a:\git\brand\env\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "a:\git\brand\app.py", line 75, in handle_post
    final_data = await adding_headers(final_data)
TypeError: object list can't be used in 'await' expression
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:14:46:58 +0000] "POST /find HTTP/1.1" 500 244 "-" "python-requests/2.24.0"
asyncio - DEBUG - Using proactor: IocpProactor
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:05:13 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:47 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:52 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:10:00 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:52 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:52 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:52 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:52 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:56 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:09:56 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:10:55 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:04 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:10:55 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:09 +0000] "POST /find HTTP/1.1" 200 1730 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:10:59 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:04 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:09 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:09 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
aiohttp.access - INFO - 127.0.0.1 [12/Sep/2020:15:11:09 +0000] "POST /find HTTP/1.1" 200 133902 "-" "python-requests/2.24.0"
